// <auto-generated />
using System;
using EJERCICIO_FINAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PROEM_PROYECTOFINALMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220428221900_Cliente Item")]
    partial class ClienteItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Cliente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SaldoCuentaCorriente")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Facturas", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"), 1L, 1);

                    b.Property<int>("ClienteCodigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("ClienteCodigo");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Items", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacturasNumero")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.HasIndex("FacturasNumero");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Pagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteCodigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<float>("Importe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCodigo");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Facturas", b =>
                {
                    b.HasOne("PROEM_PROYECTOFINALMVC.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Items", b =>
                {
                    b.HasOne("PROEM_PROYECTOFINALMVC.Models.Facturas", "Facturas")
                        .WithMany()
                        .HasForeignKey("FacturasNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("PROEM_PROYECTOFINALMVC.Models.Pagos", b =>
                {
                    b.HasOne("PROEM_PROYECTOFINALMVC.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
